apiVersion: v2
name: pokecare
description: Helm chart para la aplicación PokeCare
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: PokeCare Team
    email: example@pokecare.com

dependencies:
  - name: mongodb
    version: "12.1.31"
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: redis
    version: "17.3.14"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled