apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort  # También puedes usar LoadBalancer si estás en la nube
  selector:
    app: node-app  # Debe coincidir con el label del Deployment
  ports:    
    - protocol: TCP
      port: 80       # Puerto interno del Service
      targetPort: 3100  # Puerto del contenedor
      nodePort: 31000   # Puerto en el nodo (rango: 30000-32767)