{{- if .Values.apiGateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app: {{ .Release.Name }}
    component: api-gateway
    {{- include "pokecare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: api-gateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: api-gateway
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: api-gateway
        image: {{ .Values.global.imageRegistry }}/{{ .Values.apiGateway.image.repository }}:{{ .Values.global.imageTag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.apiGateway.image.pullPolicy }}
        ports:
        - containerPort: 80
        env:
        - name: POKEMON_SERVICE_URL
          value: "http://{{ .Release.Name }}-pokemon-service:{{ .Values.pokemonService.service.port }}"
        - name: USER_SERVICE_URL
          value: "http://{{ .Release.Name }}-user-service:{{ .Values.userService.service.port }}"
        - name: DAYCARE_SERVICE_URL
          value: "http://{{ .Release.Name }}-daycare-service:{{ .Values.daycareService.service.port }}"
        resources:
          {{- toYaml .Values.apiGateway.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app: {{ .Release.Name }}
    component: api-gateway
    {{- include "pokecare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - port: {{ .Values.apiGateway.service.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
    component: api-gateway
{{- if .Values.monitoring.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-api-gateway
  labels:
    app: {{ .Release.Name }}
    component: api-gateway
    {{- include "pokecare.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: api-gateway
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
{{- end }}
{{- end }}