{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mongodb
  labels:
    app: {{ .Release.Name }}
    {{- include "pokecare.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ printf "mongodb://%s:%s@%s-mongodb.%s.svc.cluster.local:27017/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password .Release.Name .Release.Namespace .Values.mongodb.auth.database | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
    {{- include "pokecare.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.userService.jwtSecret | default (randAlphaNum 32) | b64enc | quote }}