{{- if .Values.userService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-service
  labels:
    app: {{ .Release.Name }}
    component: user-service
    {{- include "pokecare.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.userService.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: user-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: user-service
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.global.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
      - name: user-service
        image: {{ .Values.global.imageRegistry }}/{{ .Values.userService.image.repository }}:{{ .Values.global.imageTag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.userService.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mongodb
              key: mongodb-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: jwt-secret
        resources:
          {{- toYaml .Values.userService.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-service
  labels:
    app: {{ .Release.Name }}
    component: user-service
    {{- include "pokecare.labels" . | nindent 4 }}
spec:
  type: {{ .Values.userService.service.type }}
  ports:
  - port: {{ .Values.userService.service.port }}
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: {{ .Release.Name }}
    component: user-service
{{- if .Values.monitoring.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-user-service
  labels:
    app: {{ .Release.Name }}
    component: user-service
    {{- include "pokecare.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: user-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
{{- end }}
{{- end }}