apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokecare-pokemon-service
  labels:
    app: pokecare
    component: pokemon-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokecare
      component: pokemon-service
  template:
    metadata:
      labels:
        app: pokecare
        component: pokemon-service
    spec:
      containers:
      - name: pokemon-service
        image: ${ACR_NAME}.azurecr.io/pokecare-pokemon-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: pokecare-mongodb
              key: mongodb-uri
        - name: REDIS_HOST
          value: pokecare-redis-master
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pokecare-redis
              key: redis-password
        - name: POKEAPI_BASE_URL
          value: "https://pokeapi.co/api/v2"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: pokecare-pokemon-service
  labels:
    app: pokecare
    component: pokemon-service
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: pokecare
    component: pokemon-service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pokecare-pokemon-service
  labels:
    app: pokecare
    component: pokemon-service
spec:
  selector:
    matchLabels:
      app: pokecare
      component: pokemon-service
  endpoints:
  - port: http
    path: /metrics
    interval: 15s