apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pokewebsite-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pokewebsite-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "pokewebsite-chart.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 3100
