apiVersion: v1
kind: Service
metadata:
  name: {{ include "pokewebsite-chart.name" . }}-service
spec:
  type: {{ .Values.service.type }}  # También puedes usar LoadBalancer si estás en la nube
  selector:
    app: {{ include "pokewebsite-chart.name" . }}  # Debe coincidir con el label del Deployment
  ports:    
    - protocol: TCP
      port: {{ .Values.service.port }}       # Puerto interno del Service
      targetPort: {{ .Values.service.targetPort}}  # Puerto del contenedor
      nodePort: {{ .Values.service.nodePort}}   # Puerto en el nodo (rango: 30000-32767)