name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiso para escribir en el repositorio
      pages: write     # Permiso específico para GitHub Pages
      id-token: write  # Necesario para autenticación OIDC

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install react-dnd react-dnd-html5-backend axios gh-pages

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: gh-pages -d dist
